// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_CS_ZORK.DATA_ACCESS_LAYER.Models;

namespace TP_CS_ZORK.DATA_ACCESS_LAYER.Migrations
{
    [DbContext(typeof(ZorkDbContext))]
    [Migration("20210212124806_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "French_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("CanMoveTo")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ItemRate")
                        .HasColumnType("int");

                    b.Property<int>("MonsterRate")
                        .HasColumnType("int");

                    b.Property<int>("PosX")
                        .HasColumnType("int");

                    b.Property<int>("PosY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Dammage")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("MissRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Object", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.ObjectsType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Dammage")
                        .HasColumnType("int");

                    b.Property<int>("Heal")
                        .HasColumnType("int");

                    b.Property<int>("MissRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ObjectsType");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CurrentCellId")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ObjectsId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCellId");

                    b.HasIndex("ObjectsId");

                    b.HasIndex("WeaponsId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.WeaponsType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Dammage")
                        .HasColumnType("int");

                    b.Property<int>("MissRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("WeaponsType");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Object", b =>
                {
                    b.HasOne("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.ObjectsType", "IdNavigation")
                        .WithOne("Object")
                        .HasForeignKey("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Object", "Id")
                        .HasConstraintName("FK__Objects__Id__45BE5BA9")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Player", b =>
                {
                    b.HasOne("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Cell", "CurrentCell")
                        .WithMany("Players")
                        .HasForeignKey("CurrentCellId")
                        .HasConstraintName("FK__Players__Current__41EDCAC5")
                        .IsRequired();

                    b.HasOne("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Object", "Objects")
                        .WithMany("Players")
                        .HasForeignKey("ObjectsId")
                        .HasConstraintName("FK__Players__Objects__43D61337")
                        .IsRequired();

                    b.HasOne("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Weapon", "Weapons")
                        .WithMany("Players")
                        .HasForeignKey("WeaponsId")
                        .HasConstraintName("FK__Players__Weapons__42E1EEFE")
                        .IsRequired();

                    b.Navigation("CurrentCell");

                    b.Navigation("Objects");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.WeaponsType", b =>
                {
                    b.HasOne("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Weapon", "IdNavigation")
                        .WithOne("WeaponsType")
                        .HasForeignKey("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.WeaponsType", "Id")
                        .HasConstraintName("FK__WeaponsType__Id__44CA3770")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Cell", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Object", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.ObjectsType", b =>
                {
                    b.Navigation("Object");
                });

            modelBuilder.Entity("TP_CS_ZORK.DATA_ACCESS_LAYER.Models.Weapon", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("WeaponsType");
                });
#pragma warning restore 612, 618
        }
    }
}
